### ISSUE TITLE
Issue building WPF on VS 2019 with Extras 2.0 SDK and .NET Core 2.2 SDK

### ISSUE THREAD

**Issue by zperak** [onovotny/MSBuildSdkExtras#162] opened 2019-05-13 09:11 UTC
Hi,

[ReactiveUI](https://github.com/reactiveui/reactiveui) recentrly switched to `MSBuild.Sdk.Extras` version `2.0.24` (from `1.6.68`). Now there is a problem with firing `WhenActivated` on `View` that is loaded into `ViewModelViewHost`. Details here: [#2021](https://github.com/reactiveui/ReactiveUI/issues/2021)

**Comment by onovotny** [comment] 2019-05-13 23:22
From: https://github.com/reactiveui/ReactiveUI/issues/2021#issuecomment-492020974

Looking at the binlog, nothing immediately jumps out at me. I can see that it's not importing the WindowsDesktop targets, by design, as they're not found (correctly). It's using the 2.2.x SDK to build.

I can see the Microsoft.WinFX.targets being imported by the common targets. I'm not sure what's going on here.

What I can say is this.... if it works with the .NET Core 3 Preview SDK & VS 2019, then that's my primary goal. I want to leverage as much as the built-in targets allow, and that SDK allows/supports building .NET Framework and .NET Core WPF correctly. If there's an issue there, I'd be concerned.

If, as it seems, the issue is limited to VS 2019 and the 2.2 SDK, I don't have a lot of time to spend on digging. I'll take a PR if someone can figure out what's going on though.

**Comment by onovotny** [comment] 2019-08-06 12:57
Closing due to age

**Closed by onovotny** 2019-08-06 12:57 UTC
