### ISSUE TITLE
WPF SplashScreen Build Action.

### ISSUE THREAD

**Issue by chuuddo** [onovotny/MSBuildSdkExtras#91] opened 2018-07-06 09:47 UTC
Can't set SplashScreen build action to image file from properties.
Manually added to csproj works, but splash.png not visible in solution explorer.
```xml
<Project Sdk="MSBuild.Sdk.Extras/1.6.20-preview">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <ExtrasEnableWpfProjectSetup>true</ExtrasEnableWpfProjectSetup>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Splash.png" />
    <SplashScreen Include="Splash.png" />
  </ItemGroup> 
</Project>
```
VS 15.7.4

**Comment by davkean** [comment] 2018-07-09 05:29
Dupe of that: https://github.com/dotnet/project-system/issues/2160.

**Comment by onovotny** [comment] 2018-07-29 13:53
Closing as external

**Closed by onovotny** 2018-07-29 13:53 UTC
